var X;
X = true;
PRINT($.type(X));
PRINT(typeof X);
X = function(){};
PRINT($.type(X));
PRINT(typeof X);
X = 3.14;
PRINT($.type(X));
PRINT(typeof X);
X = 'Phillip Senn';
PRINT($.type(X));
PRINT(typeof X);
X = {};
PRINT($.type(X));
PRINT(typeof X);
X = new Date();
PRINT($.type(X));
PRINT(typeof X);
X = [];
PRINT($.type(X));
PRINT(typeof X);
X = /X/;
PRINT($.type(X));
PRINT(typeof X);
